# Generated by Django 4.0.3 on 2022-08-27 17:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_products_amountmade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attr_name', models.TextField(default='')),
                ('status', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_name', models.TextField(default='')),
                ('status', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.TextField(default='')),
                ('status', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.TextField(default="Mal's store", max_length=255)),
                ('charge_amnt', models.FloatField(default=0.0)),
                ('vat', models.FloatField(default=0.0)),
                ('address', models.TextField(default='')),
                ('phone', models.BigIntegerField(default=0)),
                ('country', models.CharField(default='Ghana', max_length=70)),
                ('message', ckeditor.fields.RichTextField()),
                ('currency', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_id', models.IntegerField(default=0)),
                ('customer_name', models.IntegerField(default=0)),
                ('amount_made', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.TextField(default='')),
                ('customer_address', models.TextField(default='')),
                ('customer_phone', models.IntegerField(default=502259962)),
                ('product_name', models.IntegerField(default=0)),
                ('gross_amount', models.IntegerField(default=0)),
                ('s_charge', models.FloatField(default=0)),
                ('vat', models.FloatField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('net_amnt', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('store_name', models.TextField(default='')),
                ('status', models.IntegerField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='availability',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='brand',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='description',
            field=ckeditor.fields.RichTextField(default='test desc'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='sku',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='products',
            name='store',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='amountmade',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
