# Generated by Django 4.0.3 on 2022-09-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_alter_category_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stores',
            name='status',
            field=models.CharField(default='', max_length=10),
        ),
    ]
