# Generated by Django 4.0.3 on 2022-09-02 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_alter_attribute_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/'),
        ),
    ]
