# Generated by Django 4.0.3 on 2022-09-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0010_alter_products_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='currency',
            field=models.CharField(default='USD', max_length=5),
        ),
        migrations.AlterField(
            model_name='company',
            name='message',
            field=models.TextField(),
        ),
    ]
