# Generated by Django 4.0.3 on 2022-08-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_amountmade'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='user',
            name='lastname',
            field=models.CharField(default='steveson', max_length=85),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_group',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(max_length=85),
        ),
    ]
