# Generated by Django 4.0.3 on 2022-08-29 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_gender_user_lastname_user_user_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(default='', max_length=255)),
                ('permissions', models.TextField(default='')),
            ],
        ),
    ]
